version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/Extract_Metadata_From_ERStudio/dbp01-erstudio-extract"  # Location of Pipfile
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "fix"
    labels:
      - "dependencies"
      - "security"
