name: Update requirements.txt from Pipfile.lock

on:
  push:
    paths:
      - 'Extract_Metadata_From_ERStudio/dbp01-erstudio-extract/Pipfile.lock'

jobs:
  update-requirements:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install pipenv
        run: pip install pipenv

      - name: Generate requirements.txt
        working-directory: Extract_Metadata_From_ERStudio/dbp01-erstudio-extract
        run: pipenv lock -r > requirements.txt

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add Extract_Metadata_From_ERStudio/dbp01-erstudio-extract/requirements.txt
          git commit -m "chore: update requirements.txt from Pipfile.lock" || echo "No changes to commit"
          git push
